INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(1, 354.97, 'B3');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(15, 263.49, 'B1');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(16, 302.93, 'B2');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(17, 405.68, 'A1');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(18, 804.33, 'D');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(19, 223.56, 'C3');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(20, 223.56, 'C3');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(21, 199.03, 'L5A');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(22, 250.00, '3Parte');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(23, 275.00, '3Parte A');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(24, 290.00, '3Parte B');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(25, 285.00, '3Parte C');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(26, 1200.00, 'C');
INSERT INTO resources_rate_param (rrp_id, rrp_rate, rrp_grade) VALUES(27, 290.00, '3Parte D');
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(1, 1, 'AM Anagrafe', 'Reactive', 'MARREDDU FRANCESCA', '');
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(2, 1, 'Cross', 'Reactive', 'GIARETTO LUCA', '');
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(3, 1, 'Progetti host anagrafe', 'REACTIVE', 'AINI MARIO', '');
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(4, 1, 'Cross', 'REACTIVE', 'BARSANTI STEFANO', '');
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(5, 24, 'Progetti host anagrafe', 'KYREY', 'MIRABELLI LUIGI', '');
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(6, 1, 'AM Anagrafe e Sportello', 'REACTIVE', 'BARTOLINI STEFANO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(7, 16, 'AM Anagrafe e Sportello', 'REACTIVE', 'CALABRESE PAOLO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(8, 1, 'Progetti host anagrafe', 'REACTIVE', 'CAMMI FILIPPO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(9, 1, 'Progetti dipartimentale anagrafe', 'REACTIVE', 'COLATOSTI VALENTINO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(10, 17, 'CdC Anagrafe', 'REACTIVE', 'DE CARLI RAIMONDA', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(11, 1, 'Progetti host anagrafe', 'REACTIVE', 'DI NUNZIO ELISA', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(12, 18, 'Cross', 'REACTIVE', 'FRASCA MICHELA', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(13, 20, 'Progetti dipartimentale anagrafe', 'REACTIVE', 'FRATTINI ALESSANDRO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(14, 16, 'Progetti dipartimentale anagrafe', 'REACTIVE', 'FURLAN VALENTINO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(15, 20, 'Progetti host anagrafe', 'REACTIVE', 'IAGHER LEANDRO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(16, 1, 'Progetti dipartimentale sportello', 'REACTIVE', 'MINNITI GIUSEPPE', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(17, 16, 'Progetti dipartimentale sportello', 'REACTIVE', 'MOSCHINI SEBASTIANO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(18, 21, 'Progetti dipartimentale anagrafe', 'REACTIVE', 'ORTU STEFANO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(19, 1, 'Supporto dipartimentale', 'REACTIVE', 'RUSSO GIUSEPPE ERNESTO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(20, 16, 'AM Anagrafe', 'REACTIVE', 'SCOGNAMIGLIO CIRA', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(21, 1, 'AM Anagrafe', 'REACTIVE', 'SCOTTI TERESA', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(22, 1, 'Cross', 'REACTIVE', 'SOTTANA BARBARA', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(23, 1, 'Progetti host anagrafe', 'REACTIVE', 'TONON MARTINA', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(24, 1, 'Progetti dipartimentale anagrafe', 'REACTIVE', 'JAN MAIN MUHAMMAD FAHEEM', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(25, 22, 'Progetti dipartimentale anagrafe', 'Advancia Technology srl', 'MARCHESIELLO GIUSEPPE', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(26, 22, 'Progetti dipartimentale anagrafe', 'Advancia Technology srl', 'RUSSO GABRIEL', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(27, 23, 'Progetti dipartimentale anagrafe', 'TEHELAB', 'COZZOLINO PIPICELLI PAOLO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(28, 25, 'Progetti host sportello', 'KYREY', 'ZAMBON FABRIZIO', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(29, 17, 'Cross', 'REACTIVE', 'RISORSA A1', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(30, 1, 'Cross', 'REACTIVE', 'RISORSA B3', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(31, 16, 'Cross', 'REACTIVE', 'RISORSA B2', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(32, 26, 'Cross', 'REACTIVE', 'REPERIBILITA B3', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(33, 24, 'Progetti host anagrafe', 'KYREY', 'REPERIBILITA MIRABELLI', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(34, 1, 'Cross', 'REACTIVE', 'PLAFOND B3', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(35, 16, 'Cross', 'REACTIVE', 'PLAFOND B2', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(36, 1, 'Cross', 'REACTIVE', 'TBD Ricavo B3', NULL);
INSERT INTO resources (r_id, r_rate_param_id, r_area, r_company, r_nominative, r_number) VALUES(37, 22, 'Progetti dipartimentale sportello', 'Advancia Technology srl', 'ADVANCIA', NULL);
INSERT INTO customer (c_id, c_customer_name) VALUES(1, 'Bper nuovo');
INSERT INTO customer (c_id, c_customer_name) VALUES(2, 'Intesa San Paolo');
INSERT INTO customer_serivce (cs_id, cs_rate, customer_c_id, cs_service_name) VALUES(1, 330.00, 1, 'AMAN - Canone manutenzione Anagrafe');
INSERT INTO customer_serivce (cs_id, cs_rate, customer_c_id, cs_service_name) VALUES(4, 330.00, 1, 'RTF2 - Sportello evolutive WIDE');
INSERT INTO batch_registry (br_client_service_id, br_days_remaining, br_id, br_order_status, br_order_type, br_proceeds, br_proceeds_day_plafond, br_description, br_note, br_order, br_pm, br_expected_margin) VALUES(1, 0.00, 4, 'A', 'R', 216000.00, 200.00, 'AMAN - Canone manutenzione Anagrafe', 'Residui AN', '23E-C21092.AMAN', 'Giaretto', 8.00);
INSERT INTO batch_registry (br_client_service_id, br_days_remaining, br_id, br_order_status, br_order_type, br_proceeds, br_proceeds_day_plafond, br_description, br_note, br_order, br_pm, br_expected_margin) VALUES(4, 0.00, 5, 'A', 'R', 651.42, 0.00, 'RTF2 - Sportello evolutive WIDE', 'no', '23E-C21475.RTF2', 'Giaretto', 20.00);